/*
 * Copyrightq (c) 1997-2007 Erez Zadok <ezk@cs.stonybrook.edu>
 * Copyright (c) 2001-2007 Stony Brook University
 *
 * For specific licensing information, see the COPYING file distributed with
 * this package, or get one from
 * ftp://ftp.filesystems.org/pub/fistgen/COPYING.
 *
 * This Copyright notice must be kept intact and distributed with all
 * fistgen sources INCLUDING sources generated by fistgen.
 */
/*
 * File: fistgen/templates/Linux-2.6/fist_aux.c
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif /* HAVE_CONFIG_H */
#ifdef FISTGEN
# include "fist_sfuse.h"
#endif /* FISTGEN */
#include "fist.h"
#include "sfuse.h"
#include <linux/mount.h>


/*
 * kernel_read like function.
 * "buf" is in kernel space.
 */
ssize_t
sfuse_kernel_read(struct file *file, char *buf, size_t count, loff_t *pos)
{
        mm_segment_t old_fs;
        ssize_t ret;

        /* Read count bytes from offset pos into buf */
        old_fs = get_fs();
        set_fs(get_ds());
	ret = vfs_read (file, (void __user*)buf, count, pos);
        set_fs(old_fs);

        return ret;
}






/*
 * Local variables:
 * c-basic-offset: 4
 * End:
 */
