/*
 * sfuse.c
 * Do not edit by hand.
 * Automatically generated by fistgen.
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif /* HAVE_CONFIG_H */
#ifdef FISTGEN
# include "fist_sfuse.h"
#endif /* FISTGEN */
#include "fist.h"
#include "sfuse.h"

/* OPTIONAL CODE FOLLOWS */

