/*
 * Copyright (c) 1997-2007 Erez Zadok <ezk@cs.stonybrook.edu>
 * Copyright (c) 2001-2007 Stony Brook University
 *
 * For specific licensing information, see the COPYING file distributed with
 * this package, or get one from
 * ftp://ftp.filesystems.org/pub/fistgen/COPYING.
 *
 * This Copyright notice must be kept intact and distributed with all
 * fistgen sources INCLUDING sources generated by fistgen.
 */
/*
 * File: fistgen/templates/Linux-2.6/fist_ioctl.c
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif /* HAVE_CONFIG_H */
#ifdef FISTGEN
# include "fist_sfuse.h"
#endif /* FISTGEN */
#include "fist.h"
#include "sfuse.h"

#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

static int optcount;
static const char *progname;


void
usage(void)
{
	exit(1);
}


int
main(int argc, char *argv[])
{
	int fd, ret, val = 0;

	progname = argv[0];

	/* check that minimum number of args were specified */
	if (argc < 3)
		usage();




	/* check that at least one option was used */
	if (!optcount)
		usage();

	/* open file on which ioctl will operate */
	fd = open(argv[2], O_RDONLY);
	if (fd < 0) {
		perror(argv[2]);
		exit(1);
	}




out:
	close(fd);
	exit(0);
}

/*
 * Local variables:
 * c-basic-offset: 4
 * End:
 */
